# -*- coding: utf-8 -*-
"""sanduiche.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Bm-U6H9ciOnZEeF7nlK_x0UvCWE2Bmc
"""



def exibir_menu():
  print("\n MONTAGEM DE SANDUICHE")
  print("1 - Adicionar ingredientes")
  print("2 - Remover ingredientes do topo")
  print("3 - Ver ultimo igrediente adicionado")
  print("4 - Mostrar sanduiche")
  print("5 - Finalizar pedido")

def main():
  pilha = []

  while True:
    exibir_menu()
    opcao = input("Escolha uma opção: ")

    if opcao == "1":
      ingrediente = input("Digite qual ingrediente deseja adicionar:")
      pilha.append(ingrediente)
      print(f"'{ingrediente}' adicionado com sucesso")

    elif opcao == "2":
      if len(pilha) == 0:
        print("Sem ingredientes para remover")
      else:
        removido = pilha.pop()
        print(f"{removido} foi removido!")

    elif opcao == "3":
      if len(pilha) == 0:
        print("Não temos ingredientes para mostrar")
      else:
          print(f"O ultimo ingrediente adicionado ao sanduiche foi {pilha[-1]}")

    elif opcao == "4":
      if len(pilha)   == 0:
        print ("Sanduiche vazio")
      else:
        print("\n Seu sanduiche está assim...")
        for i , ingrediente in enumerate(pilha):
          if i == 0:
            print(f" {ingrediente}")
          else:
            print(f" {ingrediente}")
        print()

    elif opcao == "5":
      print("pedido finalizado!")
      break

    else:
      print("Opção invalida! Tente novamente")

if __name__ == "__main__":
    main()

