# -*- coding: utf-8 -*-
"""FilaDeAtendimento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lihwDkloRiKqpqz7KdI_GPNb_Df-c4F0
"""



# ---------------------------------------------------------------
# SIMULAÇÃO DE UMA FILA DE ATENDIMENTO (FIFO)
# ---------------------------------------------------------------
# Autor: Fernando Fesali & ChatGPT
# Descrição:
#   Este programa simula o funcionamento de uma fila de atendimento
#   utilizando o conceito de estrutura de dados Fila (FIFO),
#   onde o primeiro a entrar é o primeiro a sair.
# ---------------------------------------------------------------

# Importa a classe deque, que implementa uma fila eficiente em Python.
# Ela permite inserir e remover elementos tanto do início quanto do fim
# de maneira muito rápida.
from collections import deque

# Criação de duas filas:
# - uma para atendimentos normais
# - outra para atendimentos prioritários
fila_normal = deque()
fila_prioritaria = deque()

# ---------------------------------------------------------------
# Função: adicionar_pessoa()
# Descrição: adiciona uma pessoa à fila normal.
# ---------------------------------------------------------------
def adicionar_pessoa():
    # Solicita ao usuário o nome da pessoa que será adicionada
    nome = input("Digite o nome da pessoa: ").strip()

    # Verifica se o nome não está vazio
    if nome:
        # Adiciona o nome ao final da fila normal
        fila_normal.append(nome)
        print(f"{nome} foi adicionado(a) à fila normal.")
    else:
        print("Nome inválido!")

# ---------------------------------------------------------------
# Função: adicionar_prioritario()
# Descrição: adiciona uma pessoa à fila prioritária.
# ---------------------------------------------------------------
def adicionar_prioritario():
    # Solicita ao usuário o nome do atendimento prioritário
    nome = input("Digite o nome do atendimento prioritário: ").strip()

    # Verifica se o nome é válido
    if nome:
        # Adiciona ao final da fila prioritária
        fila_prioritaria.append(nome)
        print(f"{nome} foi adicionado(a) à fila prioritária.")
    else:
        print("Nome inválido!")

# ---------------------------------------------------------------
# Função: atender_pessoa()
# Descrição: remove e exibe a pessoa que será atendida.
#   - Se houver alguém na fila prioritária, essa pessoa é atendida primeiro.
#   - Caso contrário, atende a primeira pessoa da fila normal.
# ---------------------------------------------------------------
def atender_pessoa():
    # Primeiro verifica se existe alguém na fila prioritária
    if fila_prioritaria:
        # Remove o primeiro elemento (esquerda) da fila prioritária
        pessoa = fila_prioritaria.popleft()
        print(f"✅ {pessoa} (prioritário) foi atendido(a).")

    # Caso a fila prioritária esteja vazia, atende a fila normal
    elif fila_normal:
        pessoa = fila_normal.popleft()
        print(f"✅ {pessoa} foi atendido(a).")

    # Se ambas as filas estiverem vazias
    else:
        print("⚠️ Nenhuma pessoa na fila para atender.")

# ---------------------------------------------------------------
# Função: mostrar_fila()
# Descrição: exibe o estado atual das filas.
#   - Mostra as pessoas que estão na fila prioritária e normal.
# ---------------------------------------------------------------
def mostrar_fila():
    # Se ambas as filas estiverem vazias, avisa o usuário
    if not fila_prioritaria and not fila_normal:
        print("A fila está vazia.")
        return  # Sai da função

    # Mostra as pessoas que estão na fila
    print("\n=== FILA DE ATENDIMENTO ===")

    # Exibe a fila prioritária
    if fila_prioritaria:
        print("Fila Prioritária:", " → ".join(fila_prioritaria))
    else:
        print("Fila Prioritária: (vazia)")

    # Exibe a fila normal
    if fila_normal:
        print("Fila Normal:     ", " → ".join(fila_normal))
    else:
        print("Fila Normal:      (vazia)")

    print("============================\n")

# ---------------------------------------------------------------
# Loop principal (menu interativo)
# ---------------------------------------------------------------
while True:
    # Exibe as opções do menu
    print("\n--- MENU DE ATENDIMENTO ---")
    print("1 - Adicionar pessoa à fila")
    print("2 - Adicionar atendimento prioritário")
    print("3 - Atender pessoa")
    print("4 - Mostrar fila")
    print("5 - Sair")

    # Solicita que o usuário escolha uma opção
    opcao = input("Escolha uma opção: ").strip()

    # Analisa a opção escolhida e executa a função correspondente
    if opcao == "1":
        adicionar_pessoa()
    elif opcao == "2":
        adicionar_prioritario()
    elif opcao == "3":
        atender_pessoa()
    elif opcao == "4":
        mostrar_fila()
    elif opcao == "5":
        # Encerra o programa
        print("Encerrando o programa... Até logo!")
        break
    else:
        # Caso o usuário digite algo fora das opções válidas
        print("⚠️ Opção inválida! Tente novamente.")
